package loginform;

import Control.Delivery_Operations;
import Control.Orders_Operations;
import Control.Pharmacist_operations;
import Control.Products_Operations;
import Control.customers_operations;
import Modeling.Customers_Model;
import Modeling.Delivery_Model;
import Modeling.Pharmacist_Model;
import Modeling.Products_Model;
import javax.swing.JOptionPane;
/**
 *
 * @author Seifeldin Ahmed
 */
public class MakeOrder extends javax.swing.JFrame {


    public String mobileNumberPattern = "^01[0125][0-9]{8}$";
    public String DatePattern = "^(?:(?:31(\\/|-|\\.)(?:0?[13578]|1[02]))\\1|(?:(?:29|30)(\\/|-|\\.)(?:0?[13-9]|1[0-2])\\2))(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$|^(?:29(\\/|-|\\.)0?2\\3(?:(?:(?:1[6-9]|[2-9]\\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\\d|2[0-8])(\\/|-|\\.)(?:(?:0?[1-9])|(?:1[0-2]))\\4(?:(?:1[6-9]|[2-9]\\d)?\\d{2})$";

    public MakeOrder() {
        initComponents();
         Add.setEnabled(false);  
         deliveryID.setVisible(false);
         deliveryPhone.setVisible(false);
         deliveryName.setVisible(false);
         label_DelveriyID.setVisible(false);
         label_deliveryName.setVisible(false);
         label_deliveryphone.setVisible(false);
    }
    
 public boolean validateFields() {
             
        // order info 
        String order_price = price.getText();
        String order_date = date.getText();
        String Payment_Type= PaymentType.getText();
        
        // product info
        String order_product = product.getText();
        String order_quantity = pharmacistID.getText();
        
        // pharmacist info 
        String Ph_ID = pharmacistID.getText();
        
        // delivery info 
        boolean delivery_status=true;
       if(DeliveryOption.getSelectedIndex() == 1) // means yes
        {
            delivery_status = !deliveryID.getText().equals("") && !deliveryName.getText().equals("") && deliveryPhone.getText().matches(mobileNumberPattern);
        }

        return !Payment_Type.equals("") && !Ph_ID.equals("") && !order_price.equals("") && order_date.matches(DatePattern) && !order_product.equals("") && !order_quantity.equals("") && delivery_status;
    
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtname1 = new javax.swing.JTextField();
        txtname2 = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        Street = new javax.swing.JTextField();
        Add = new button.mybutton();
        gender = new javax.swing.JComboBox<>();
        txtphone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        product = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pharmacistID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        DeliveryOption = new javax.swing.JComboBox<>();
        label_deliveryName = new javax.swing.JLabel();
        deliveryName = new javax.swing.JTextField();
        label_deliveryphone = new javax.swing.JLabel();
        deliveryPhone = new javax.swing.JTextField();
        deliveryID = new javax.swing.JTextField();
        label_DelveriyID = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        quantity1 = new javax.swing.JTextField();
        PaymentType = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-button.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(6, 107, 138,80));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Make New Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Untitled-1 (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 115));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 110, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Information");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last name");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("City");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Street");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, -1, -1));

        txtname1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtname1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtname1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtname1MouseExited(evt);
            }
        });
        txtname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname1ActionPerformed(evt);
            }
        });
        txtname1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtname1KeyReleased(evt);
            }
        });
        jPanel2.add(txtname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 139, -1));

        txtname2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtname2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtname2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtname2MouseExited(evt);
            }
        });
        txtname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtname2ActionPerformed(evt);
            }
        });
        txtname2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtname2KeyReleased(evt);
            }
        });
        jPanel2.add(txtname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 139, -1));

        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });
        jPanel2.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 139, -1));

        Street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetActionPerformed(evt);
            }
        });
        Street.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StreetKeyReleased(evt);
            }
        });
        jPanel2.add(Street, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 139, -1));

        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.setForeground(new java.awt.Color(6, 107, 138));
        Add.setText("Add");
        Add.setBorderColor(new java.awt.Color(255, 255, 255));
        Add.setBorderPainted(false);
        Add.setColorClick(new java.awt.Color(153, 204, 255));
        Add.setColorOver(new java.awt.Color(204, 204, 204));
        Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Add.setRadius(10);
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
        });
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel2.add(Add, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 83, 41));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderActionPerformed(evt);
            }
        });
        jPanel2.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, -1, -1));

        txtphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtphoneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtphoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtphoneMouseExited(evt);
            }
        });
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel2.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 139, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone Number");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("First Name");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer Information");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceActionPerformed(evt);
            }
        });
        price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                priceKeyReleased(evt);
            }
        });
        jPanel2.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 139, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Date");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
        });
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 139, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Product");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productActionPerformed(evt);
            }
        });
        product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                productKeyReleased(evt);
            }
        });
        jPanel2.add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 139, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pharmcasit ID");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        pharmacistID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacistIDActionPerformed(evt);
            }
        });
        pharmacistID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pharmacistIDKeyReleased(evt);
            }
        });
        jPanel2.add(pharmacistID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 139, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Delivery Option");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        DeliveryOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        DeliveryOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliveryOptionActionPerformed(evt);
            }
        });
        jPanel2.add(DeliveryOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, -1, -1));

        label_deliveryName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_deliveryName.setForeground(new java.awt.Color(255, 255, 255));
        label_deliveryName.setText("Delivery Name");
        jPanel2.add(label_deliveryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        deliveryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryNameActionPerformed(evt);
            }
        });
        deliveryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                deliveryNameKeyReleased(evt);
            }
        });
        jPanel2.add(deliveryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 139, -1));

        label_deliveryphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_deliveryphone.setForeground(new java.awt.Color(255, 255, 255));
        label_deliveryphone.setText("Phone Number");
        jPanel2.add(label_deliveryphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        deliveryPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryPhoneActionPerformed(evt);
            }
        });
        deliveryPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                deliveryPhoneKeyReleased(evt);
            }
        });
        jPanel2.add(deliveryPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 139, -1));

        deliveryID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deliveryIDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveryIDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveryIDMouseExited(evt);
            }
        });
        deliveryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryIDActionPerformed(evt);
            }
        });
        deliveryID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                deliveryIDKeyReleased(evt);
            }
        });
        jPanel2.add(deliveryID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 139, -1));

        label_DelveriyID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_DelveriyID.setForeground(new java.awt.Color(255, 255, 255));
        label_DelveriyID.setText("Delivery ID");
        jPanel2.add(label_DelveriyID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Quantity");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        quantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantity1ActionPerformed(evt);
            }
        });
        quantity1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantity1KeyReleased(evt);
            }
        });
        jPanel2.add(quantity1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 139, -1));

        PaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentTypeActionPerformed(evt);
            }
        });
        PaymentType.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaymentTypeKeyReleased(evt);
            }
        });
        jPanel2.add(PaymentType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 139, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Payment Type");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 710, 520));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/17973908.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1ActionPerformed

    private void txtname1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtname1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname1KeyReleased

    private void txtname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname2ActionPerformed

    private void txtname2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtname2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtname2KeyReleased

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityKeyReleased

    private void StreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetActionPerformed

    private void StreetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StreetKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetKeyReleased

    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
        if (validateFields()) {
            
            boolean terminated = false;
            int order_id=0;
            int delivery_id=0;
         ///////////////////////////////////////////////////////////////// PRODUCT SECTION ////////////////////////////////////////////////////////////////////////////////
           // search product 
           Products_Model product_object =Products_Operations.Search_Product(product.getText());
           if(product_object!=null)
           {
                int stored_quantity = product_object.getQuantity();
                int entered_quantity =Integer.parseInt(quantity1.getText().trim());
                int remaining_quantity;
                if(stored_quantity<entered_quantity) 
                     remaining_quantity = 0 ;
                else
                     remaining_quantity= stored_quantity - entered_quantity;
                Products_Operations.Edit_Product(product.getText(), product_object.getPrice(), product_object.getExpired_date(), remaining_quantity);
           }
           else
           {
                JOptionPane.showMessageDialog(null, "Product Name is Wrong ", "Message", JOptionPane.WARNING_MESSAGE);
                terminated = true;
           }
         //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

         
         
         //////////////////////////////////////////////////////////////// PHARMACIST SECTION //////////////////////////////////////////////////////////////////////////////
             int id =Integer.parseInt(pharmacistID.getText().trim());
             // search pharmacist 
             Pharmacist_Model pharmacist_opbect = Pharmacist_operations.Search_Pharmacist(id);
             if ( pharmacist_opbect == null)
             {
                JOptionPane.showMessageDialog(null, "There's No Pharmacist with This ID", "Message", JOptionPane.WARNING_MESSAGE);
                 terminated = true;
             }
         ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

                  
         
          //////////////////////////////////////////////////////////////// Delivery Option//////////////////////////////////////////////////////////////////////////////////             
          if(!terminated)  
          {  
             if(DeliveryOption.getSelectedIndex()==1) // means yes 
                {
                     delivery_id = Integer.parseInt(deliveryID.getText().trim());
                     Delivery_Model delivrey_object = Delivery_Operations.Search(Integer.parseInt(deliveryID.getText().trim()));
                     if(delivrey_object==null)
                      Delivery_Operations.insert_OrderData(delivery_id, deliveryPhone.getText(), deliveryName.getText());   
                       
                }
          }
         /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////  

         
         
         
         /////////////////////////////////////////////////////////////////// ORDER SECTION  ////////////////////////////////////////////////////////////////////////////////     
          if(!terminated)  
          { 
            // insert order data  
             Orders_Operations.insert_OrderData(Integer.parseInt(price.getText().trim()),date.getText(),PaymentType.getText(),delivery_id);
             // search order number 
             order_id= Orders_Operations.Return_Order_Number(Integer.parseInt(price.getText()),date.getText(),PaymentType.getText());
          }         
         /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
       

         
           
         /////////////////////////////////////////////////////////////// CUSTOMER SECTION ////////////////////////////////////////////////////////////////////////////////////
          int Customer_id=1; // restricted 
          if(!terminated)  
          { 
            if(txtphone.getText().matches(mobileNumberPattern) && !txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtcity.getText().equals("") && !Street.getText().equals(""))  
             { 
                 // search customer ID 
                Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
                if(Customer_object != null)
                    {
                        Customer_id= Customer_object.getCustomer_id();
                    }        
                if(Customer_id==1) // means customer not found 
                  // insert customer data 
                   { 
                        customers_operations.insert_CustomerData(txtname1.getText(), txtname2.getText(),txtcity.getText(), Street.getText(),(String) gender.getSelectedItem(), txtphone.getText());
                        // search customer ID again
                         Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
                         Customer_id= Customer_object.getCustomer_id();
                    }
               }
          }
         ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
 
         
         
         
          /////////////////////////////////////////////////////////////////////////////// INSERT ORDER RELATION //////////////////////////////////////////////////////////// 
          if(!terminated)
          {
             // insert to data to order_relation table with customer information
             Orders_Operations.insert_Order_Relation(Integer.parseInt(pharmacistID.getText()), Customer_id,product.getText(), order_id);      
             Orders obj = new Orders();
             obj.show_table();
             rond.order_object= obj;
             obj.setVisible(true);
             this.dispose();
          }
          ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
               

        } else {
            JOptionPane.showMessageDialog(null, "Please Enter Correct information","Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_AddMouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddActionPerformed

    private void genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Orders gg =new Orders();
        this.dispose();
        gg.show_table();
        gg.setVisible(true);
        
    }//GEN-LAST:event_backMouseClicked

    private void priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceActionPerformed

    private void priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_priceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_priceKeyReleased

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_dateKeyReleased

    private void productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productActionPerformed

    private void productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_productKeyReleased

    private void pharmacistIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacistIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacistIDActionPerformed

    private void pharmacistIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pharmacistIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_pharmacistIDKeyReleased

    private void DeliveryOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliveryOptionActionPerformed
        if(DeliveryOption.getSelectedIndex() == 1) // means yes
        {
            deliveryID.setVisible(true);
            deliveryPhone.setVisible(true);
            deliveryName.setVisible(true);
            label_DelveriyID.setVisible(true);
            label_deliveryName.setVisible(true);
            label_deliveryphone.setVisible(true);
        }
        else  // means no
        {
            deliveryID.setVisible(false);
            deliveryPhone.setVisible(false);
            deliveryName.setVisible(false);
            label_DelveriyID.setVisible(false);
            label_deliveryName.setVisible(false);
            label_deliveryphone.setVisible(false);
        }
        
        
    }//GEN-LAST:event_DeliveryOptionActionPerformed

    private void deliveryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryNameActionPerformed

    private void deliveryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deliveryNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryNameKeyReleased

    private void deliveryPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryPhoneActionPerformed

    private void deliveryPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deliveryPhoneKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryPhoneKeyReleased

    private void deliveryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryIDActionPerformed

    private void deliveryIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deliveryIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_deliveryIDKeyReleased

    private void quantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity1ActionPerformed

    private void quantity1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantity1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_quantity1KeyReleased

    private void PaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentTypeActionPerformed

    private void PaymentTypeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaymentTypeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentTypeKeyReleased

    private void txtname1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname1MouseEntered
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname1MouseEntered

    private void txtname2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname2MouseEntered
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname2MouseEntered

    private void txtphoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtphoneMouseEntered
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtphoneMouseEntered

    private void deliveryIDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryIDMouseEntered
            if(!deliveryID.getText().trim().isEmpty())
            { 
                Delivery_Model delivrey_object = Delivery_Operations.Search(Integer.parseInt(deliveryID.getText().trim()));
                if(delivrey_object!=null)
                 {
                    deliveryName.setText(delivrey_object.getName());
                    deliveryPhone.setText(delivrey_object.getPhonenumber());
                 }
            }
    }//GEN-LAST:event_deliveryIDMouseEntered

    private void deliveryIDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryIDMouseExited
            if(!deliveryID.getText().trim().isEmpty())
            { 
                Delivery_Model delivrey_object = Delivery_Operations.Search(Integer.parseInt(deliveryID.getText().trim()));
                if(delivrey_object!=null)
                 {
                    deliveryName.setText(delivrey_object.getName());
                    deliveryPhone.setText(delivrey_object.getPhonenumber());
                 }
            }
    }//GEN-LAST:event_deliveryIDMouseExited

    private void deliveryIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryIDMouseClicked
            if(!deliveryID.getText().trim().isEmpty())
            { 
                Delivery_Model delivrey_object = Delivery_Operations.Search(Integer.parseInt(deliveryID.getText().trim()));
                if(delivrey_object!=null)
                 {
                    deliveryName.setText(delivrey_object.getName());
                    deliveryPhone.setText(delivrey_object.getPhonenumber());
                 }
            }
    }//GEN-LAST:event_deliveryIDMouseClicked

    private void txtname1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname1MouseClicked
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname1MouseClicked

    private void txtname1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname1MouseExited
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname1MouseExited

    private void txtname2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname2MouseExited
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname2MouseExited

    private void txtphoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtphoneMouseExited
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtphoneMouseExited

    private void txtphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtphoneMouseClicked
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtphoneMouseClicked

    private void txtname2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtname2MouseClicked
            if(!txtname1.getText().equals("") && !txtname2.getText().equals("") && !txtphone.getText().equals(""))  
             {
               Customers_Model Customer_object = customers_operations.Return_Customer_ID(txtname1.getText(), txtname2.getText(),txtphone.getText());
               if(Customer_object != null)
                {
                    txtcity.setText(Customer_object.getCity());
                    Street.setText(Customer_object.getStreet());
                    gender.setSelectedItem(Customer_object.getGender());
                }  
           }
    }//GEN-LAST:event_txtname2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.mybutton Add;
    private javax.swing.JComboBox<String> DeliveryOption;
    private javax.swing.JTextField PaymentType;
    private javax.swing.JTextField Street;
    private javax.swing.JLabel back;
    private javax.swing.JTextField date;
    private javax.swing.JTextField deliveryID;
    private javax.swing.JTextField deliveryName;
    private javax.swing.JTextField deliveryPhone;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label_DelveriyID;
    private javax.swing.JLabel label_deliveryName;
    private javax.swing.JLabel label_deliveryphone;
    private javax.swing.JTextField pharmacistID;
    private javax.swing.JTextField price;
    private javax.swing.JTextField product;
    private javax.swing.JTextField quantity1;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtname2;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
