/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import Control.Reservation_Operations;
import Control.customers_operations;
import Modeling.Customers_Model;
import Modeling.Reservation_Model;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmed Sherif
 */
public class Reservations extends javax.swing.JFrame {

    /**
     * Creates new form Reservations
     */
    private ArrayList<Reservation_Model> arr;
    private int row_number = 0;
    public Reservations() {
        initComponents();
        tableDark1.fixTable(jScrollPane1);
        tableDark1.setColumnAlignment(0, JLabel.CENTER);
        tableDark1.setCellAlignment(0, JLabel.CENTER);
        tableDark1.setColumnAlignment(1, JLabel.CENTER);
        tableDark1.setCellAlignment(1, JLabel.CENTER);
    }
    public void show_table() {
        DefaultTableModel mm = (DefaultTableModel) tableDark1.getModel();
        arr = Reservation_Operations.get_ReservationData();
        Object[] row = new Object[5];
         for (int i = 0; i < arr.size(); i++) {
            row[0] = arr.get(i).getPH_ID(); 
            row[1] = arr.get(i).getCU_ID();
            row[2] = arr.get(i).getProduct_Name();
            row[3] = arr.get(i).getQuantity();
            row[4] = arr.get(i).getDate();
            
            mm.insertRow(i, row);
          
        }
    
        // Mouse Event
        tableDark1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                row_number = tableDark1.getSelectedRow();
            }
        }
       );
 }
         public void show_table(ArrayList<Reservation_Model> arr) {
        DefaultTableModel mm = (DefaultTableModel) tableDark1.getModel();
        Object[] row = new Object[5];
         for (int i = 0; i < arr.size(); i++) {
            row[0] = arr.get(i).getPH_ID(); 
            row[1] = arr.get(i).getCU_ID();
            row[2] = arr.get(i).getProduct_Name();
            row[3] = arr.get(i).getQuantity();
            row[4] = arr.get(i).getDate();
            mm.insertRow(i, row);
          
        }
                tableDark1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                row_number = tableDark1.getSelectedRow();
            }
        }
       );
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDark1 = new tabledark.TableDark();
        txtSearch = new javax.swing.JTextField();
        addButton = new button.mybutton();
        searchButton = new button.mybutton();
        deleteButton = new button.mybutton();
        editButton = new button.mybutton();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back-button.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        tableDark1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Pharmacist", "Customer", "Product", "Quantity", "Date"
            }
        ));
        jScrollPane1.setViewportView(tableDark1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 680, 220));

        txtSearch.setText("Pharmacist id");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, 30));

        addButton.setBackground(new java.awt.Color(6, 107, 138));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-user.png"))); // NOI18N
        addButton.setText("Add");
        addButton.setBorderColor(new java.awt.Color(255, 255, 255));
        addButton.setColorClick(new java.awt.Color(0, 153, 153));
        addButton.setMaximumSize(new java.awt.Dimension(75, 25));
        addButton.setMinimumSize(new java.awt.Dimension(75, 25));
        addButton.setPreferredSize(new java.awt.Dimension(75, 25));
        addButton.setRadius(10);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        addButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addButtonKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addButtonKeyReleased(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 80, 30));

        searchButton.setBackground(new java.awt.Color(6, 107, 138));
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setBorderColor(new java.awt.Color(255, 255, 255));
        searchButton.setColorClick(new java.awt.Color(0, 153, 153));
        searchButton.setMaximumSize(new java.awt.Dimension(75, 25));
        searchButton.setMinimumSize(new java.awt.Dimension(75, 25));
        searchButton.setPreferredSize(new java.awt.Dimension(75, 25));
        searchButton.setRadius(10);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 80, 30));

        deleteButton.setBackground(new java.awt.Color(6, 107, 138));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/x (2).png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorderColor(new java.awt.Color(255, 255, 255));
        deleteButton.setColorClick(new java.awt.Color(0, 153, 153));
        deleteButton.setMaximumSize(new java.awt.Dimension(75, 25));
        deleteButton.setMinimumSize(new java.awt.Dimension(75, 25));
        deleteButton.setPreferredSize(new java.awt.Dimension(75, 25));
        deleteButton.setRadius(10);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 90, 30));

        editButton.setBackground(new java.awt.Color(6, 107, 138));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit.png"))); // NOI18N
        editButton.setText("Edit");
        editButton.setBorderColor(new java.awt.Color(255, 255, 255));
        editButton.setColorClick(new java.awt.Color(0, 153, 153));
        editButton.setMaximumSize(new java.awt.Dimension(75, 25));
        editButton.setMinimumSize(new java.awt.Dimension(75, 25));
        editButton.setPreferredSize(new java.awt.Dimension(75, 25));
        editButton.setRadius(10);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
        });
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 90, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/booking.png"))); // NOI18N
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setMaximumSize(new java.awt.Dimension(40, 40));
        jLabel6.setRequestFocusEnabled(false);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(6, 107, 138));
        jTextField2.setText("Reservation");
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (login.Manager) {
            rond obj = new rond();
            obj.setVisible(true);
            this.dispose();
        } else {
            phar_rond obj = new phar_rond();
            obj.setVisible(true);
            this.dispose();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void addButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyPressed

    }//GEN-LAST:event_addButtonKeyPressed

    private void addButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addButtonKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonKeyReleased

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        reservationAdd obj = new reservationAdd();
        obj.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_addButtonMouseClicked

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        reservationEdit obj = new reservationEdit(arr.get(row_number).getPH_ID(),arr.get(row_number).getCU_ID(),arr.get(row_number).getProduct_Name());
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editButtonMouseClicked

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       if (txtSearch.getText().isEmpty()) {
        } else {
            ArrayList<Reservation_Model> obj = Reservation_Operations.Search_Reservation(Integer.parseInt(txtSearch.getText()));

            if (obj != null) {
               this.dispose();
                Reservations gg = new Reservations();
                gg.show_table(obj);
                gg.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "ID Not Found", "Message", JOptionPane.WARNING_MESSAGE);

            }
        } 
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
      int PH_id = arr.get(row_number).getPH_ID();
       int CU_ID =arr.get(row_number).getCU_ID();
       String productName=arr.get(row_number).getProduct_Name();
        Reservation_Operations.Delete_Reservation(PH_id, CU_ID, productName);
        this.dispose(); 
        Reservations gg = new Reservations();
        gg.show_table();
        gg.setVisible(true);
        JOptionPane.showMessageDialog(null, "reservation has been Deleted Successfully", "Message", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.mybutton addButton;
    private button.mybutton deleteButton;
    private button.mybutton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private button.mybutton searchButton;
    private tabledark.TableDark tableDark1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
